spring.application.name=qrcode-generator
cloudinary.cloud-name={CLOUDINARY_CLOUD_NAME}
cloudinary.api-key={CLOUDINARY_API_SECRETS}
cloudinary.api-secret={CLOUDINARY_API_SECRETS}
server.port=${PORT:8080}

